export default {
  permissions: [
    {
      action: 'plugin::content-manager.explorer.create',
      subject: 'plugin::users-permissions.user',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: [
          'username',
          'email',
          'provider',
          'password',
          'resetPasswordToken',
          'confirmationToken',
          'confirmed',
          'blocked',
          'role',
          'firstName',
          'lastName',
          'center',
          'phoneNumber',
        ],
      },
    },
    {
      action: 'plugin::content-manager.explorer.read',
      subject: 'plugin::users-permissions.user',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: [
          'username',
          'email',
          'provider',
          'password',
          'resetPasswordToken',
          'confirmationToken',
          'confirmed',
          'blocked',
          'role',
          'firstName',
          'lastName',
          'center',
          'phoneNumber',
        ],
      },
    },
    {
      action: 'plugin::content-manager.explorer.update',
      subject: 'plugin::users-permissions.user',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: [
          'username',
          'email',
          'provider',
          'password',
          'resetPasswordToken',
          'confirmationToken',
          'confirmed',
          'blocked',
          'role',
          'firstName',
          'lastName',
          'center',
          'phoneNumber',
        ],
      },
    },
    {
      action: 'plugin::content-manager.explorer.delete',
      subject: 'plugin::users-permissions.user',
      properties: {},
      conditions: ['admin::is-my-centre-data'],
    },
    {
      action: 'plugin::content-manager.explorer.read',
      subject: 'api::center.center',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: [
          'name',
          'region',
          'displayText',
          'logo',
          'lastImportDate',
          'zohobooks.clientId',
          'zohobooks.clientSecret',
          'zohobooks.accessToken',
          'zohobooks.refreshToken',
          'zohobooks.domain',
          'zohobooks.organizationId',
          'paymentHandler',
          'defaultDueAmount',
          'defaultPaymentDate',
        ],
      },
    },
    {
      action: 'plugin::content-manager.explorer.create',
      subject: 'api::child.child',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: [
          'firstName',
          'lastName',
          'gender',
          'houseNumber',
          'streetName',
          'city',
          'postcode',
          'center',
          'subjects',
          'parents',
          'school',
          'schoolYear',
          'status',
          'enrollmentDate',
          'statusLog.from',
          'statusLog.to',
          'statusLog.date',
          'childHash',
          'slots',
          'enquiryDate',
          'formType',
          'referralCode',
          'notes',
          'paymentDate',
          'isEarlyLearner',
          'isDue',
          'dueAmount',
          'paymentAmount',
        ],
      },
    },
    {
      action: 'plugin::content-manager.explorer.read',
      subject: 'api::child.child',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: [
          'firstName',
          'lastName',
          'gender',
          'houseNumber',
          'streetName',
          'city',
          'postcode',
          'center',
          'subjects',
          'parents',
          'school',
          'schoolYear',
          'status',
          'enrollmentDate',
          'statusLog.from',
          'statusLog.to',
          'statusLog.date',
          'childHash',
          'slots',
          'enquiryDate',
          'formType',
          'referralCode',
          'notes',
          'paymentDate',
          'isEarlyLearner',
          'isDue',
          'dueAmount',
          'paymentAmount',
        ],
      },
    },
    {
      action: 'plugin::content-manager.explorer.update',
      subject: 'api::child.child',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: [
          'firstName',
          'lastName',
          'gender',
          'houseNumber',
          'streetName',
          'city',
          'postcode',
          'center',
          'subjects',
          'parents',
          'school',
          'schoolYear',
          'status',
          'enrollmentDate',
          'statusLog.from',
          'statusLog.to',
          'statusLog.date',
          'childHash',
          'slots',
          'enquiryDate',
          'formType',
          'referralCode',
          'notes',
          'paymentDate',
          'isEarlyLearner',
          'isDue',
          'dueAmount',
          'paymentAmount',
        ],
      },
    },
    {
      action: 'plugin::content-manager.explorer.delete',
      subject: 'api::child.child',
      properties: {},
      conditions: ['admin::is-my-centre-data'],
    },
    {
      action: 'plugin::content-manager.explorer.create',
      subject: 'api::log-book.log-book',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: [
          'signatureIn',
          'student',
          'parent',
          'center',
          'guest.firstName',
          'guest.lastName',
          'guest.phoneNumber',
          'guest.email',
          'staff',
          'type',
          'signInTime',
          'signOutTime',
          'signatureOut',
        ],
      },
    },
    {
      action: 'plugin::content-manager.explorer.read',
      subject: 'api::log-book.log-book',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: [
          'signatureIn',
          'student',
          'parent',
          'center',
          'guest.firstName',
          'guest.lastName',
          'guest.phoneNumber',
          'guest.email',
          'staff',
          'type',
          'signInTime',
          'signOutTime',
          'signatureOut',
        ],
      },
    },
    {
      action: 'plugin::content-manager.explorer.delete',
      subject: 'api::log-book.log-book',
      properties: {},
      conditions: ['admin::is-my-centre-data'],
    },
    {
      action: 'plugin::content-manager.explorer.create',
      subject: 'api::parent.parent',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: ['firstName', 'lastName', 'email', 'contactNumber', 'children', 'center'],
      },
    },
    {
      action: 'plugin::content-manager.explorer.read',
      subject: 'api::parent.parent',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: ['firstName', 'lastName', 'email', 'contactNumber', 'children', 'center'],
      },
    },
    {
      action: 'plugin::content-manager.explorer.update',
      subject: 'api::parent.parent',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: ['firstName', 'lastName', 'email', 'contactNumber', 'children', 'center'],
      },
    },
    {
      action: 'plugin::content-manager.explorer.delete',
      subject: 'api::parent.parent',
      properties: {},
      conditions: ['admin::is-my-centre-data'],
    },
    {
      action: 'plugin::content-manager.explorer.read',
      subject: 'api::school.school',
      conditions: [],
      properties: {
        fields: ['name', 'city', 'postcode'],
      },
    },
    {
      action: 'plugin::content-manager.explorer.create',
      subject: 'api::slot.slot',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: ['center', 'name', 'day', 'startTime', 'endTime', 'children'],
      },
    },
    {
      action: 'plugin::content-manager.explorer.read',
      subject: 'api::slot.slot',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: ['center', 'name', 'day', 'startTime', 'endTime', 'children'],
      },
    },
    {
      action: 'plugin::content-manager.explorer.update',
      subject: 'api::slot.slot',
      conditions: ['admin::is-my-centre-data'],
      properties: {
        fields: ['center', 'name', 'day', 'startTime', 'endTime', 'children'],
      },
    },
    {
      action: 'plugin::content-manager.explorer.delete',
      subject: 'api::slot.slot',
      properties: {},
      conditions: ['admin::is-my-centre-data'],
    },
    {
      action: 'plugin::content-manager.explorer.read',
      subject: 'api::subject.subject',
      conditions: [],
      properties: {
        fields: ['name'],
      },
    },
  ],
};
