name: Deploy to VM - Prod

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/app/centre-manager-prod/frontend
            git pull origin master
            npm install
            npm run build:app
            rm -rf /var/www/app-prod/*
            cp dist/* /var/www/app-prod/ -r
            npm run build:kiosk
            rm -rf /var/www/kiosk-prod/*
            cp dist/* /var/www/kiosk-prod/ -r
            cd /home/app/centre-manager-prod/backend
            git pull origin master
            npm install
            npm run build
            pm2 restart 1
